name: CI

on:
  push:
    branches: [ main, develop, beta ]

  pull_request:
    branches: [ main, develop ]

jobs:
  release:
    if: github.event_name == 'push' && contains('
      refs/heads/main
      refs/heads/beta
      ', github.ref)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Publish with Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
